version: '3.9'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./requirements.txt:/app/requirements.txt
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      WEBHOOK_URL: "${WEBHOOK_URL}"
